services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    working_dir: /app
    # entrypoint: ["sleep", "infinity"]